using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using UrlShortener.Api.Data;
using UrlShortener.Api.Dtos;
using UrlShortener.Api.Models;

namespace UrlShortener.Api.Services;

/// <summary>
/// Orchestrates creation, resolution, click recording and analytics for short URLs.
/// Caching strategy: resolved (shortCode -> ShortUrl) lookups are cached in-memory for a
/// short TTL since redirects are the hottest, highest-QPS path. Writes (create, click count
/// increments) invalidate/bypass the cache. See ARCHITECTURE.md "Caching".
/// </summary>
public class UrlShortenerService : IUrlShortenerService
{
    private readonly AppDbContext _db;
    private readonly IShortCodeGenerator _codeGenerator;
    private readonly IMemoryCache _cache;
    private readonly ILogger<UrlShortenerService> _logger;
    private static readonly TimeSpan CacheTtl = TimeSpan.FromMinutes(5);

    public UrlShortenerService(
        AppDbContext db,
        IShortCodeGenerator codeGenerator,
        IMemoryCache cache,
        ILogger<UrlShortenerService> logger)
    {
        _db = db;
        _codeGenerator = codeGenerator;
        _cache = cache;
        _logger = logger;
    }

    public async Task<CreateUrlResult> CreateAsync(
        string originalUrl,
        string? customAlias,
        int? expiresInDays,
        string? idempotencyKey,
        CancellationToken ct)
    {
        if (!UrlValidator.TryValidate(originalUrl, out _, out var validationError))
        {
            return new CreateUrlResult(CreateUrlResultStatus.ValidationError, null, validationError);
        }

        // Idempotency: if caller supplies a key we've seen before, return the existing record
        // instead of creating a duplicate. Protects against client retries on network blips.
        if (!string.IsNullOrWhiteSpace(idempotencyKey))
        {
            var existing = await _db.ShortUrls
                .FirstOrDefaultAsync(s => s.IdempotencyKey == idempotencyKey, ct);
            if (existing is not null)
            {
                return new CreateUrlResult(CreateUrlResultStatus.IdempotentReplay, existing, null);
            }
        }

        if (customAlias is not null)
        {
            if (!UrlValidator.IsValidAlias(customAlias))
            {
                return new CreateUrlResult(CreateUrlResultStatus.ValidationError, null,
                    "Custom alias must be 3-16 alphanumeric characters (with optional - or _).");
            }

            var taken = await _db.ShortUrls.AnyAsync(s => s.ShortCode == customAlias, ct);
            if (taken)
            {
                return new CreateUrlResult(CreateUrlResultStatus.AliasTaken, null,
                    $"Alias '{customAlias}' is already in use.");
            }
        }

        var entity = new ShortUrl
        {
            OriginalUrl = originalUrl,
            CreatedAtUtc = DateTime.UtcNow,
            ExpiresAtUtc = expiresInDays.HasValue ? DateTime.UtcNow.AddDays(expiresInDays.Value) : null,
            IdempotencyKey = idempotencyKey,
            IsActive = true,
            // Temporary placeholder; real code assigned after Id is generated by the DB (below).
            ShortCode = customAlias ?? "_pending_"
        };

        _db.ShortUrls.Add(entity);
        await _db.SaveChangesAsync(ct); // assigns entity.Id

        if (customAlias is null)
        {
            entity.ShortCode = _codeGenerator.FromId(entity.Id);
            await _db.SaveChangesAsync(ct);
        }

        _logger.LogInformation("Created short URL {ShortCode} -> {OriginalUrl}", entity.ShortCode, entity.OriginalUrl);
        return new CreateUrlResult(CreateUrlResultStatus.Created, entity, null);
    }

    public async Task<ResolveResult> ResolveAsync(string shortCode, CancellationToken ct)
    {
        var cacheKey = $"shorturl:{shortCode}";

        if (_cache.TryGetValue<ShortUrl>(cacheKey, out var cached) && cached is not null)
        {
            return Evaluate(cached);
        }

        var entity = await _db.ShortUrls.AsNoTracking()
            .FirstOrDefaultAsync(s => s.ShortCode == shortCode, ct);

        if (entity is null)
        {
            return new ResolveResult(ResolveResultStatus.NotFound, null);
        }

        _cache.Set(cacheKey, entity, CacheTtl);
        return Evaluate(entity);
    }

    private static ResolveResult Evaluate(ShortUrl entity)
    {
        if (!entity.IsActive)
        {
            return new ResolveResult(ResolveResultStatus.Inactive, entity);
        }
        if (entity.ExpiresAtUtc.HasValue && entity.ExpiresAtUtc.Value < DateTime.UtcNow)
        {
            return new ResolveResult(ResolveResultStatus.Expired, entity);
        }
        return new ResolveResult(ResolveResultStatus.Found, entity);
    }

    public async Task RecordClickAsync(long shortUrlId, string? referrer, string? userAgent, string? ipHash, CancellationToken ct)
    {
        // Fire-and-forget-safe: failures here must never break the redirect response itself.
        // The caller (endpoint) wraps this in try/catch and logs but always 302s regardless.
        await _db.Database.BeginTransactionAsync(ct);
        try
        {
            _db.ClickEvents.Add(new ClickEvent
            {
                ShortUrlId = shortUrlId,
                ClickedAtUtc = DateTime.UtcNow,
                Referrer = Truncate(referrer, 256),
                UserAgent = Truncate(userAgent, 256),
                IpHash = ipHash
            });

            var url = await _db.ShortUrls.FirstAsync(s => s.Id == shortUrlId, ct);
            url.ClickCount += 1;

            await _db.SaveChangesAsync(ct);
            await _db.Database.CommitTransactionAsync(ct);
        }
        catch
        {
            await _db.Database.RollbackTransactionAsync(ct);
            throw;
        }
    }

    public async Task<AnalyticsResponse?> GetAnalyticsAsync(string shortCode, CancellationToken ct)
    {
        var entity = await _db.ShortUrls.AsNoTracking()
            .FirstOrDefaultAsync(s => s.ShortCode == shortCode, ct);
        if (entity is null) return null;

        var clicks = await _db.ClickEvents.AsNoTracking()
            .Where(c => c.ShortUrlId == entity.Id)
            .ToListAsync(ct);

        var byDay = clicks
            .GroupBy(c => DateOnly.FromDateTime(c.ClickedAtUtc))
            .Select(g => new DailyClickCount(g.Key, g.Count()))
            .OrderBy(d => d.Date)
            .ToList();

        var topReferrers = clicks
            .GroupBy(c => string.IsNullOrWhiteSpace(c.Referrer) ? "(direct)" : c.Referrer!)
            .Select(g => new ReferrerCount(g.Key, g.Count()))
            .OrderByDescending(r => r.Count)
            .Take(10)
            .ToList();

        return new AnalyticsResponse(
            entity.ShortCode,
            entity.OriginalUrl,
            entity.ClickCount,
            clicks.Count > 0 ? clicks.Max(c => c.ClickedAtUtc) : null,
            byDay,
            topReferrers
        );
    }

    private static string? Truncate(string? value, int maxLength) =>
        value is null ? null : value.Length <= maxLength ? value : value[..maxLength];
}
